-- =============================================================================
-- CrypticOwl — MySQL 8.0+ Schema
-- Equivalent of 001_initial.sql (PostgreSQL) adapted for MySQL 8.0.
--
-- Key differences vs PostgreSQL version:
--   • No built-in auth.users — includes a `users` table for identity
--   • No Row Level Security (RLS) — enforce access in application layer / API
--   • UUID()  replaces gen_random_uuid()
--   • JSON    replaces JSONB
--   • No partial indexes (WHERE clause) — use standard indexes instead
--   • No FILTER clause in aggregates — use CASE WHEN instead
--   • ON DUPLICATE KEY UPDATE replaces ON CONFLICT ... DO UPDATE
--   • INSERT IGNORE            replaces ON CONFLICT ... DO NOTHING
--   • STORED generated columns use MySQL syntax
--   • DELIMITER $$ for stored procedures / functions
--   • TEXT[] (PostgreSQL arrays) stored as JSON arrays
--   • TIMESTAMPTZ → DATETIME(3) (UTC, stored without TZ offset; store all UTC)
--   • GENERATED BY DEFAULT AS IDENTITY → AUTO_INCREMENT
-- =============================================================================

-- Use a UTF-8 database; run this in the target DB or prefix each table with db name.
-- CREATE DATABASE IF NOT EXISTS crypticowl CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
-- USE crypticowl;


-- ─── LOOKUP TABLES ───────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS clue_wordplay_types (
  id          VARCHAR(50)  NOT NULL PRIMARY KEY,
  label       VARCHAR(100) NOT NULL,
  description TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT IGNORE INTO clue_wordplay_types (id, label, description) VALUES
  ('anagram',            'Anagram',            'Letters of the fodder rearranged'),
  ('reversal',           'Reversal',            'Word or phrase written backwards'),
  ('container',          'Container',           'One word placed inside another'),
  ('hidden',             'Hidden Word',         'Answer concealed within the clue text'),
  ('deletion',           'Deletion',            'Letters removed from a word'),
  ('charade',            'Charade',             'Parts read consecutively without a join indicator'),
  ('homophone',          'Homophone',           'Answer sounds like another word'),
  ('double_definition',  'Double Definition',   'Two separate definitions, no wordplay'),
  ('cryptic_definition', 'Cryptic Definition',  'Whole clue is a misleading definition'),
  ('andlit',             '& Lit',               'Whole clue is simultaneously wordplay and definition'),
  ('compound',           'Compound',            'Two or more wordplay types used together');


CREATE TABLE IF NOT EXISTS clue_indicator_types (
  id          VARCHAR(50)  NOT NULL PRIMARY KEY,
  label       VARCHAR(100) NOT NULL,
  description TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT IGNORE INTO clue_indicator_types (id, label, description) VALUES
  ('anagram',             'Anagram',             'Signals letters to rearrange (e.g. "mixed up", "broken")'),
  ('reversal',            'Reversal',            'Signals reading backwards (e.g. "back", "returning")'),
  ('container',           'Container',           'Signals insertion (e.g. "holding", "around", "outside")'),
  ('hidden',              'Hidden',              'Signals concealment (e.g. "in", "some of", "part of")'),
  ('deletion',            'Deletion',            'Signals letter removal (e.g. "mostly", "beheaded", "heartless")'),
  ('homophone',           'Homophone',           'Signals sounds-like (e.g. "we hear", "reportedly", "in speech")'),
  ('initial_letters',     'Initial Letters',     'Signals first letters (e.g. "initially", "leaders of")'),
  ('final_letters',       'Final Letters',       'Signals last letters (e.g. "ultimately", "ends of")'),
  ('alternating_letters', 'Alternating Letters', 'Signals odd/even letters (e.g. "regularly", "alternatively")'),
  ('spoonerism',          'Spoonerism',          'Signals swapped initial consonants');


-- ─── USERS ───────────────────────────────────────────────────────────────────
-- MySQL has no built-in auth layer. This table stores identity for users
-- authenticated via OAuth (Google, etc.) or email/password in your backend.
-- The `provider_id` is the unique ID returned by the OAuth provider.

CREATE TABLE IF NOT EXISTS users (
  id           CHAR(36)     NOT NULL PRIMARY KEY DEFAULT (UUID()),
  email        VARCHAR(320) NOT NULL UNIQUE,
  name         VARCHAR(255),
  picture_url  VARCHAR(2048),
  -- OAuth provider ("google", "github", etc.) and their stable user ID
  provider     VARCHAR(50)  NOT NULL DEFAULT 'google',
  provider_id  VARCHAR(255) NOT NULL,
  UNIQUE KEY uq_users_provider (provider, provider_id),
  created_at   DATETIME(3)  NOT NULL DEFAULT (NOW(3)),
  updated_at   DATETIME(3)  NOT NULL DEFAULT (NOW(3))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- ─── CLUES ───────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS clues (
  id               CHAR(36)       NOT NULL PRIMARY KEY DEFAULT (UUID()),

  -- clue_text is UNIQUE so automated inserts can use INSERT IGNORE
  clue_text        TEXT           NOT NULL,
  -- MySQL TEXT columns can't have a UNIQUE constraint directly — use a hash index
  -- via a generated column for exact de-duplication
  clue_text_hash   CHAR(64)       GENERATED ALWAYS AS (SHA2(clue_text, 256)) STORED NOT NULL,
  UNIQUE KEY uq_clue_text_hash (clue_text_hash),

  -- answer: uppercase letters only, no spaces/hyphens
  answer           VARCHAR(50)    NOT NULL,
  CONSTRAINT chk_answer_upper CHECK (answer = UPPER(answer)),
  CONSTRAINT chk_answer_alpha  CHECK (answer REGEXP '^[A-Z]+$'),

  -- Derived: total letter count. MySQL generated column, always correct.
  answer_length    TINYINT UNSIGNED GENERATED ALWAYS AS (CHAR_LENGTH(answer)) STORED NOT NULL,

  -- Display letter-count pattern: "5", "3,4", "2-3"
  answer_pattern   VARCHAR(20)    NOT NULL,
  CONSTRAINT chk_answer_pattern CHECK (answer_pattern REGEXP '^[0-9][0-9,\\-]*$'),

  -- Prevents same answer with same display pattern appearing twice
  UNIQUE KEY uq_answer_pattern (answer(50), answer_pattern),

  -- Wordplay metadata
  primary_type     VARCHAR(50)    NOT NULL,
  CONSTRAINT fk_clues_type FOREIGN KEY (primary_type) REFERENCES clue_wordplay_types(id),

  definition_text  TEXT           NOT NULL,
  wordplay_summary TEXT           NOT NULL,

  -- Frontend display data: JSON arrays (validates as JSON in MySQL 8+)
  clue_parts       JSON           NOT NULL DEFAULT (JSON_ARRAY()),
  hints            JSON           NOT NULL DEFAULT (JSON_ARRAY()),
  CONSTRAINT chk_clue_parts_array CHECK (JSON_TYPE(clue_parts) = 'ARRAY'),
  CONSTRAINT chk_hints_array      CHECK (JSON_TYPE(hints)      = 'ARRAY'),

  -- Tags stored as JSON array (e.g. ["british-english", "easy"])
  -- In PostgreSQL this is TEXT[]; in MySQL we use JSON
  tags             JSON           NOT NULL DEFAULT (JSON_ARRAY()),

  difficulty       ENUM('easy','medium','hard','expert') NOT NULL DEFAULT 'medium',
  author           VARCHAR(255),
  notes            TEXT,  -- internal only, never sent to the frontend

  created_at       DATETIME(3)    NOT NULL DEFAULT (NOW(3)),
  updated_at       DATETIME(3)    NOT NULL DEFAULT (NOW(3)),

  INDEX idx_clues_type       (primary_type),
  INDEX idx_clues_difficulty (difficulty)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- ─── DAILY PUZZLES ───────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS daily_puzzles (
  id              CHAR(36)   NOT NULL PRIMARY KEY DEFAULT (UUID()),
  date            DATE       NOT NULL,
  clue_id         CHAR(36)   NOT NULL,
  CONSTRAINT fk_dp_clue FOREIGN KEY (clue_id) REFERENCES clues(id) ON DELETE CASCADE,

  published       TINYINT(1) NOT NULL DEFAULT 0,

  -- 1-based position for ordered multi-clue days; always 1 for current single-clue format
  sequence_number SMALLINT   NOT NULL DEFAULT 1,

  -- Sequential puzzle number shown to users ("Puzzle #42")
  -- AUTO_INCREMENT on a non-PK column requires it to be a key
  puzzle_number   INT        NOT NULL AUTO_INCREMENT,
  KEY key_puzzle_number (puzzle_number),  -- required for AUTO_INCREMENT on non-PK
  UNIQUE KEY uq_puzzle_number  (puzzle_number),
  UNIQUE KEY uq_date_clue      (date, clue_id),
  UNIQUE KEY uq_date_sequence  (date, sequence_number),

  INDEX idx_dp_date_published (date, published),
  INDEX idx_dp_clue_published (clue_id, published)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Note: AUTO_INCREMENT on a non-PK column is only supported by InnoDB when the column
-- is the leftmost column of some key. The KEY definition above satisfies this.
-- To seed a specific starting number (e.g. puzzle_number = 42), run:
--   ALTER TABLE daily_puzzles AUTO_INCREMENT = 42;
-- before the first INSERT. Or set puzzle_number explicitly in the INSERT.


-- ─── CLUE COMPONENTS ─────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS clue_components (
  id             CHAR(36)     NOT NULL PRIMARY KEY DEFAULT (UUID()),
  clue_id        CHAR(36)     NOT NULL,
  CONSTRAINT fk_cc_clue FOREIGN KEY (clue_id) REFERENCES clues(id) ON DELETE CASCADE,

  step_order     SMALLINT     NOT NULL,

  role           ENUM(
    'definition', 'indicator', 'fodder',
    'container_outer', 'container_inner',
    'link_word', 'result'
  ) NOT NULL,

  clue_text      TEXT         NOT NULL,
  derived_text   TEXT,

  -- Only populated when role = 'indicator'; NULL otherwise
  indicator_type VARCHAR(50),
  CONSTRAINT fk_cc_indicator FOREIGN KEY (indicator_type) REFERENCES clue_indicator_types(id),
  CONSTRAINT chk_indicator_coupling CHECK (
    (role = 'indicator' AND indicator_type IS NOT NULL)
    OR
    (role <> 'indicator' AND indicator_type IS NULL)
  ),

  explanation    TEXT,
  created_at     DATETIME(3)  NOT NULL DEFAULT (NOW(3)),

  UNIQUE KEY uq_cc_clue_step (clue_id, step_order),
  INDEX idx_cc_clue_order    (clue_id, step_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- ─── USER STATS ──────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS user_stats (
  user_id        CHAR(36)    NOT NULL PRIMARY KEY,
  CONSTRAINT fk_us_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,

  streak_count   INT         NOT NULL DEFAULT 0,
  best_streak    INT         NOT NULL DEFAULT 0,
  last_solved    DATE,
  total_solved   INT         NOT NULL DEFAULT 0,
  xp             INT         NOT NULL DEFAULT 0,
  level          SMALLINT    NOT NULL DEFAULT 1,
  updated_at     DATETIME(3) NOT NULL DEFAULT (NOW(3))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- ─── SOLVE HISTORY ───────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS solve_history (
  id                  CHAR(36)    NOT NULL PRIMARY KEY DEFAULT (UUID()),
  user_id             CHAR(36)    NOT NULL,
  CONSTRAINT fk_sh_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  clue_id             CHAR(36)    NOT NULL,
  CONSTRAINT fk_sh_clue FOREIGN KEY (clue_id) REFERENCES clues(id) ON DELETE CASCADE,

  puzzle_number       INT         NOT NULL,
  hints_used          SMALLINT    NOT NULL DEFAULT 0,
  CONSTRAINT chk_hints_gte_zero CHECK (hints_used >= 0),
  wrong_attempts      INT         NOT NULL DEFAULT 0,
  CONSTRAINT chk_wrong_gte_zero CHECK (wrong_attempts >= 0),
  xp_earned           INT         NOT NULL DEFAULT 0,
  solve_time_seconds  INT,
  CONSTRAINT chk_solve_time_pos CHECK (solve_time_seconds IS NULL OR solve_time_seconds > 0),

  solved_at           DATETIME(3) NOT NULL DEFAULT (NOW(3)),

  UNIQUE KEY uq_sh_user_clue     (user_id, clue_id),
  INDEX idx_sh_user_solved_at    (user_id, solved_at DESC),
  INDEX idx_sh_clue_hints        (clue_id, hints_used),
  INDEX idx_sh_clue              (clue_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- ─── CLUE REACTIONS ──────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS clue_reactions (
  user_id     CHAR(36)                  NOT NULL,
  CONSTRAINT fk_cr_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  clue_id     CHAR(36)                  NOT NULL,
  CONSTRAINT fk_cr_clue FOREIGN KEY (clue_id) REFERENCES clues(id) ON DELETE CASCADE,

  reaction    ENUM('like', 'dislike')   NOT NULL,
  updated_at  DATETIME(3)               NOT NULL DEFAULT (NOW(3)),

  PRIMARY KEY (user_id, clue_id),
  INDEX idx_cr_clue_reaction (clue_id, reaction)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- ─── VIEWS ───────────────────────────────────────────────────────────────────

-- Aggregate reaction counts per clue (no user_id exposed)
CREATE OR REPLACE VIEW clue_reaction_counts AS
SELECT
  clue_id,
  SUM(reaction = 'like')    AS likes,
  SUM(reaction = 'dislike') AS dislikes,
  COUNT(*)                   AS total
FROM clue_reactions
GROUP BY clue_id;


-- Per-clue solve analytics for clue authors / admin dashboard.
-- MySQL 8 does not support FILTER (WHERE ...) in aggregates — use CASE WHEN.
CREATE OR REPLACE VIEW clue_solve_stats AS
SELECT
  c.id                                                                             AS clue_id,
  dp.date,
  c.primary_type,
  c.difficulty,
  c.author,

  COUNT(DISTINCT sh.user_id)                                                       AS total_solves,

  -- Hint funnel
  SUM(CASE WHEN sh.hints_used >= 1 THEN 1 ELSE 0 END)                            AS hint_1_opens,
  SUM(CASE WHEN sh.hints_used >= 2 THEN 1 ELSE 0 END)                            AS hint_2_opens,
  SUM(CASE WHEN sh.hints_used >= 3 THEN 1 ELSE 0 END)                            AS hint_3_opens,
  SUM(CASE WHEN sh.hints_used >= 4 THEN 1 ELSE 0 END)                            AS hint_4_opens,

  -- Difficulty signals
  ROUND(AVG(sh.hints_used),            2)                                          AS avg_hints_used,
  ROUND(AVG(sh.solve_time_seconds),    0)                                          AS avg_solve_seconds,
  ROUND(AVG(sh.wrong_attempts),        2)                                          AS avg_wrong_attempts,
  SUM(CASE WHEN sh.hints_used = 0 THEN 1 ELSE 0 END)                             AS zero_hint_solves,

  -- Quality signals
  COALESCE(rc.likes,    0)                                                          AS likes,
  COALESCE(rc.dislikes, 0)                                                          AS dislikes,
  CASE
    WHEN COALESCE(rc.total, 0) = 0 THEN NULL
    ELSE ROUND(rc.likes * 100.0 / rc.total, 1)
  END                                                                               AS like_pct

FROM clues c
LEFT JOIN daily_puzzles        dp ON dp.clue_id = c.id
LEFT JOIN solve_history        sh ON sh.clue_id = c.id
LEFT JOIN clue_reaction_counts rc ON rc.clue_id = c.id
GROUP BY
  c.id, dp.date, c.primary_type, c.difficulty, c.author,
  rc.likes, rc.dislikes, rc.total;


-- ─── TRIGGERS: auto-update updated_at ────────────────────────────────────────

DELIMITER $$

CREATE TRIGGER clues_set_updated_at
  BEFORE UPDATE ON clues
  FOR EACH ROW
BEGIN
  SET NEW.updated_at = NOW(3);
END$$

CREATE TRIGGER users_set_updated_at
  BEFORE UPDATE ON users
  FOR EACH ROW
BEGIN
  SET NEW.updated_at = NOW(3);
END$$

CREATE TRIGGER user_stats_set_updated_at
  BEFORE UPDATE ON user_stats
  FOR EACH ROW
BEGIN
  SET NEW.updated_at = NOW(3);
END$$

CREATE TRIGGER clue_reactions_set_updated_at
  BEFORE UPDATE ON clue_reactions
  FOR EACH ROW
BEGIN
  SET NEW.updated_at = NOW(3);
END$$


-- ─── STORED PROCEDURE: record_solve ──────────────────────────────────────────
-- Atomically inserts a solve record and updates user_stats.
-- MySQL does not support functions returning BOOLEAN from DML directly;
-- use a procedure with an OUT parameter instead.
--
-- Call from application layer:
--   CALL record_solve(p_user_id, p_clue_id, p_puzzle_number,
--                     p_hints_used, p_wrong_attempts, p_xp_earned,
--                     p_solve_time_seconds, p_client_date, @result);
--   SELECT @result;  -- 1 = new solve, 0 = already solved
--
-- p_client_date: the user's local date as 'YYYY-MM-DD'.
--   Pass NULL to fall back to CURDATE() (UTC).
--   Non-null value prevents streak breaks for users in timezones ahead of UTC.

CREATE PROCEDURE record_solve(
  IN  p_user_id             CHAR(36),
  IN  p_clue_id             CHAR(36),
  IN  p_puzzle_number       INT,
  IN  p_hints_used          SMALLINT,
  IN  p_wrong_attempts      INT,
  IN  p_xp_earned           INT,
  IN  p_solve_time_seconds  INT,      -- NULL if not tracked
  IN  p_client_date         DATE,     -- NULL to use CURDATE()
  OUT p_result              TINYINT   -- 1 = inserted, 0 = already existed
)
SQL SECURITY DEFINER
BEGIN
  DECLARE v_today    DATE;
  DECLARE v_last     DATE;
  DECLARE v_streak   INT;
  DECLARE v_best     INT;

  SET v_today = COALESCE(p_client_date, CURDATE());

  -- Insert solve record; skip silently if already solved (unique constraint)
  INSERT IGNORE INTO solve_history (
    id, user_id, clue_id, puzzle_number,
    hints_used, wrong_attempts, xp_earned, solve_time_seconds
  ) VALUES (
    UUID(), p_user_id, p_clue_id, p_puzzle_number,
    p_hints_used, p_wrong_attempts, p_xp_earned, p_solve_time_seconds
  );

  -- ROW_COUNT() = 1 means the INSERT happened; 0 means duplicate was skipped
  IF ROW_COUNT() = 0 THEN
    SET p_result = 0;
  ELSE
    -- Ensure user_stats row exists
    INSERT IGNORE INTO user_stats (user_id) VALUES (p_user_id);

    -- Read current streak state
    SELECT last_solved, streak_count, best_streak
    INTO   v_last, v_streak, v_best
    FROM   user_stats
    WHERE  user_id = p_user_id;

    -- Recalculate streak (NULL-safe: new users have NULL last_solved)
    SET v_streak = CASE
      WHEN v_last IS NULL               THEN 1              -- first solve ever
      WHEN v_last = DATE_SUB(v_today, INTERVAL 1 DAY)
                                        THEN v_streak + 1  -- consecutive day
      WHEN v_last = v_today             THEN v_streak       -- same day (idempotency edge)
      ELSE                                   1              -- streak broken
    END;

    SET v_best = GREATEST(v_best, v_streak);

    -- Atomic stats update
    UPDATE user_stats SET
      streak_count = v_streak,
      best_streak  = v_best,
      last_solved  = v_today,
      total_solved = total_solved + 1,
      xp           = xp + p_xp_earned
      -- level is computed client-side; omitted here to avoid duplicating formula
    WHERE user_id = p_user_id;

    SET p_result = 1;
  END IF;
END$$

DELIMITER ;


-- ─── SEED: PUZZLE #42 ────────────────────────────────────────────────────────
-- Uses INSERT IGNORE so re-running this script is safe.

SET @clue_id = UUID();

INSERT IGNORE INTO clues (
  id, clue_text, answer, answer_pattern,
  primary_type, definition_text, wordplay_summary,
  difficulty, clue_parts, hints
) VALUES (
  @clue_id,
  'Pears mixed up to form a weapon (5)',
  'SPEAR',
  '5',
  'anagram',
  'a weapon',
  'PEARS is an anagram of SPEAR',
  'easy',
  JSON_ARRAY(
    JSON_OBJECT('text', 'Pears',      'type', 'fodder'),
    JSON_OBJECT('text', ' mixed up ', 'type', 'indicator'),
    JSON_OBJECT('text', 'to form ',   'type', 'link'),
    JSON_OBJECT('text', 'a weapon',   'type', 'definition'),
    JSON_OBJECT('text', ' (5)',       'type', NULL)
  ),
  JSON_ARRAY(
    JSON_OBJECT(
      'id', 1, 'title', 'Definition Location',
      'text', 'The definition is at the end of the clue.',
      'highlight', 'a weapon',
      'mascot_comment', 'The definition is always at the start or end of a cryptic clue. Look at the end! 👀',
      'color', '#3B82F6', 'bg', '#EFF6FF', 'bg_dark', '#0D1F35', 'border', '#93C5FD'
    ),
    JSON_OBJECT(
      'id', 2, 'title', 'Spot the Indicator',
      'text', '"Mixed up" is an anagram indicator — it tells you the letters need rearranging.',
      'highlight', 'mixed up',
      'mascot_comment', '"Mixed up" signals an anagram — letters are getting scrambled! 🔀',
      'color', '#7C3AED', 'bg', '#F5F3FF', 'bg_dark', '#1A0F35', 'border', '#C4B5FD'
    ),
    JSON_OBJECT(
      'id', 3, 'title', 'Find the Fodder',
      'text', '"PEARS" is the fodder — these are the letters you need to rearrange!',
      'highlight', 'Pears',
      'mascot_comment', 'P-E-A-R-S... these are your building blocks! Try shuffling them! ✨',
      'color', '#F97316', 'bg', '#FFF7ED', 'bg_dark', '#2A1505', 'border', '#FED7AA'
    ),
    JSON_OBJECT(
      'id', 4, 'title', 'Full Breakdown',
      'text', 'Rearrange the letters of PEARS to get a 5-letter weapon.',
      'highlight', NULL,
      'mascot_comment', 'You''ve got all the pieces! P-E-A-R-S → _ _ _ _ _ 🎯',
      'color', '#059669', 'bg', '#ECFDF5', 'bg_dark', '#062010', 'border', '#6EE7B7'
    )
  )
);

-- Set puzzle_number sequence to start at 42 so the first auto-increment is 42.
-- If your table already has rows, adjust accordingly.
ALTER TABLE daily_puzzles AUTO_INCREMENT = 42;

INSERT IGNORE INTO daily_puzzles (id, date, clue_id, published, sequence_number, puzzle_number)
SELECT UUID(), '2026-04-06', id, 1, 1, 42
FROM   clues
WHERE  clue_text_hash = SHA2('Pears mixed up to form a weapon (5)', 256)
LIMIT  1;

-- Clue components for #42
INSERT IGNORE INTO clue_components (id, clue_id, step_order, role, clue_text, derived_text, indicator_type, explanation)
SELECT
  UUID(), c.id, v.step_order, v.role, v.clue_text, v.derived_text, v.indicator_type, v.explanation
FROM clues c
JOIN (
  SELECT 1 AS step_order, 'definition' AS role, 'a weapon' AS clue_text, 'SPEAR' AS derived_text, NULL AS indicator_type, 'SPEAR = a weapon (plain definition)' AS explanation
  UNION ALL
  SELECT 2, 'indicator', 'mixed up', NULL, 'anagram', '"mixed up" signals an anagram'
  UNION ALL
  SELECT 3, 'fodder',    'Pears',    'SPEAR', NULL, 'PEARS → rearrange all 5 letters → SPEAR'
) v
WHERE c.clue_text_hash = SHA2('Pears mixed up to form a weapon (5)', 256);
